modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="the_elder_scrolls_craft"
version="1.0.0"
displayName="The_Elder_Scrolls_Craft"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="USER, MCreator"
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.the_elder_scrolls_craft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



